# Generated by Django 5.2.6 on 2025-09-25 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='artist',
            new_name='Artist',
        ),
    ]
