# Generated by Django 5.2.6 on 2025-09-25 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_artist_user_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='unfollowed',
            field=models.ManyToManyField(blank=True, related_name='unfollowed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
