# Generated by Django 5.2.6 on 2025-09-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_alter_album_unique_together'),
        ('songs', '0002_alter_song_cover_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('album', 'title')},
        ),
    ]
