# Generated by Django 5.2.6 on 2025-09-26 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_alter_song_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='song',
            name='likes',
        ),
        migrations.AddField(
            model_name='song',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, related_name='disliked_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
